### ISSUE TITLE
[BUG] Krane cannot find redisgraph

### ISSUE THREAD

**Issue by Joseph94m** [appvia/krane#186]
### Short issue description

I have deployed krane and redisgraph according to the installation guide + prerequisites (roles, rolebindings, SA)

The deployment + services seem to start fine as shown below.

![Screenshot 2021-08-06 at 17 36 04](https://user-images.githubusercontent.com/40126230/128535545-6a4a6805-ceb7-4fcc-92f9-668eb3303c48.png)
![Screenshot 2021-08-06 at 17 36 18](https://user-images.githubusercontent.com/40126230/128535587-5d6347e4-4845-4a4f-bf53-1209cd33ed34.png)

The logs of the redisgraph seem fine.
![Screenshot 2021-08-06 at 17 36 29](https://user-images.githubusercontent.com/40126230/128535606-44191bdf-0085-4f6d-9b22-b8e0606af83e.png)

Krane cannot connect to the redisgraph however.
![Screenshot 2021-08-06 at 17 36 40](https://user-images.githubusercontent.com/40126230/128535627-2deadc78-e972-449b-af49-e589c670a0d0.png)

This is the service configuration for redisgraph:
![Screenshot 2021-08-06 at 17 37 38](https://user-images.githubusercontent.com/40126230/128535737-ec1ae7ee-e667-44e3-9f7f-7e5510bb6664.png)

Krane version: latest
redisgraph version: 1.99.7
OS (Linux/Mac/Windows..): centos7
Docker version 18.06.2
Kubernetes version: 1.17.4

I connected to the krane pod/container and ran some commands, it just seems that nc has a problem with the 'redisgraph' string because it immediately returns an error.

![image](https://user-images.githubusercontent.com/40126230/128537056-505f4eb2-e802-4d5b-8373-0506c51379cc.png)

**Comment by marcinc** [comment]
Thanks @Joseph94m for reporting the issue. Are both `krane` and `redisgraph` deployed to the same namespace? Could you check/verify that network policies don't block traffic between the two services please? Would be great if you could confirm that. In the meantime we'll try to recreate the issue on our end.

**Comment by Joseph94m** [comment]
Problem solved. I just hadn't correctly applied https://github.com/appvia/krane/blob/master/k8s/one-time/prerequisites.yaml
