### ISSUE TITLE
[BUG] Run the report first

### ISSUE THREAD

**Issue by Joseph94m** [appvia/krane#188]
@marcinc hi, it's me again, not sure if this goes here or if I should ask it on the community chat.

### Short issue description
So after having (i hope) *correctly* applied the deployments files, krane does start but it keeps crashing with the following error:
![Screenshot 2021-08-13 at 09 39 20](https://user-images.githubusercontent.com/40126230/129321859-5a0d56a8-4c94-4512-b0de-d78d2b2b41d6.png)

The message in itself is obvious... I did look into the scripts and I saw that the code does try to run a report first... I guess it's failing? But there are no additional logs to debug.  So, i am not entirely sure if this is a misconfiguration from my side or if it's a bug.

![image](https://user-images.githubusercontent.com/40126230/129322464-b0c9840d-007a-4ba1-ae32-79425f451a58.png)
 

Krane version: latest
redisgraph version: 1.99.7
OS (Linux/Mac/Windows..): centos7
Docker version 18.06.2
Kubernetes version: 1.17.4

**Comment by marcinc** [comment]
Hi @Joseph94m. Welcome back and thanks for the issue report. We’ll look into thiis. Could be some sort of race condition.
