### ISSUE TITLE
[FR] Why Schema only with bidirectional arrows ?

### ISSUE THREAD

**Issue by sergiomarotco** [appvia/krane#227]
### Is your feature request related to a problem? Please describe.
nope

### Describe the solution you'd like
It would be more correct to draw arrows unidirectional where it is more correct

**Comment by marcinc** [comment]
Hello @sergiomarotco. Could you expand on the issue a little bit please?

**Comment by sergiomarotco** [comment]
![image](https://github.com/user-attachments/assets/d37ad3bc-7664-456c-a83f-d52cdc976731)

arrows always point in both directions
