### ISSUE TITLE
[FR] Product helm chart for easy deployment

### ISSUE THREAD

**Issue by jon-shanks** [appvia/krane#238]
### Is your feature request related to a problem? Please describe.

Nope, just simplicity of deployment

### Describe the solution you'd like
 a simple helm chart to deploy this with

### Describe alternatives you've considered
none

### Additional context
none

**Comment by marcinc** [comment]
This has been addressed by #245. 

Pre-req: [Helm CLI](https://helm.sh/docs/intro/install/)

```
$ helm repo add appvia https://appvia.github.io/krane
$ helm repo update
$ helm install krane appvia/krane --namespace krane --create-namespace
```
