### ISSUE TITLE
[BUG] Krane is not compatible with Kubernetes 1.25

### ISSUE THREAD

**Issue by fjammes** [appvia/krane#297]
### Short issue description

Krane is not compatible with k8s-1.15 API:

```
$ kubectl exec -it -n krane krane-59bc887964-zvxmj --  bash
bash-5.1$ krane report --incluster
INFO: This may take several seconds to complete...
INFO: ERR Invalid graph operation on empty key. Graph `rbac-default` will be created.
error: HTTP status code 404, the server could not find the requested resource for GET https://kubernetes.default.svc/apis/policy/v1beta1.
```

Krane version : 0.1.0
OS : Linux
Kubernetes version: 1.15
Kubernetes distribution : kind 

### How can we reproduce the issue?

Install `krane` inside Kubernetes-1.25 and run `krane report --incluster` inside the `krane` pod.

### Suggestions on how to fix the issue (OPTIONAL)

Updade `krane` so that is support k8s-1.25 API.

**Comment by marcinc** [comment]
Hi @fjammes. Thank for reporting the issue. Fix should land shortly.

**Comment by marcinc** [comment]
This should be now resolved.
